<a href="https://colab.research.google.com/github/afifahsalsa/stupen/blob/main/Afifah_Salsabila_Kelompok_2_Praktik1_Modul3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# !. Upload database

In [1]:
#import library
import sqlite3
import pandas as pd

In [2]:
con = sqlite3.connect("iowa_sales.db")

# 2. Buang tabel yang tidak ada kaitanyya dengan database

In [3]:
#Cek data dalam database
query = """SELECT name FROM sqlite_master WHERE type='table';"""
tables = pd.read_sql_query(query, con)
print(tables)

       name
0  employee

In [4]:
#drop table yang tidak dibutuhkan dalam database
query = """ DROP TABLE employee """
con.execute(query)

In [5]:
#cek kembali database tersebut
query = """SELECT name FROM sqlite_master WHERE type='table';"""
tables = pd.read_sql_query(query, con)
print(tables)

Empty DataFrame
Columns: [name]
Index: []

# 3. Buat tabel dengan nama "stock" dan masukkan data ke dalam tabel stock

In [6]:
#create table stock
create_table1 = """ CREATE TABLE stock (
  item_description VARCHAR NOT NULL,
  stock_available INTEGER NOT NULL,
  grade_rating FLOAT NOT NULL
)"""

In [7]:
#cek apakah table benar" berhasil dibuat
try:
    con.execute(create_table1)
    print("Tabel berhasil dibuat!")
except Exception as e:
    print("Terjadi kesalahan")
    print(e)

Tabel berhasil dibuat!

In [8]:
#cek info dalam table stock
query = """ PRAGMA table_info(stock); """
pd.read_sql_query(query, con)

   cid              name     type  notnull dflt_value  pk
0    0  item_description  VARCHAR        1       None   0
1    1   stock_available  INTEGER        1       None   0
2    2      grade_rating    FLOAT        1       None   0

In [9]:
#masukkan data dalam table stock
query = """ INSERT INTO stock VALUES
('JAGERMEISTER MINI MEISTERS', 3437, 3),
('MAKERS MARK W/HOLIDAY ORNAMENT', 4821, 5),
('CROWN ROYAL W/2 GLASSES', 2095, 4),
('BLACK VELVET TRAVELER', 2731, 5),
('CANADIAN RICH & RARE PEACH', 1661, 4),
('FOUR ROSES SMALL BATCH', 1837, 5),
('OLD FORESTER BOURBON 86 PRF', 3990, 5),
('TEN HIGH PET', 1490, 4),
('ABSOLUT APEACH', 3451, 5),
('FRIS DANISH VODKA', 3033, 4),
('WESTERN SON BLUEBERRY', 1906, 4),
('CRUZAN STRAWBERRY', 1584, 5),
('BAILEYS VANILLA CINNAMON', 3025, 5),
('KAHLUA COFFEE', 4309, 4),
('DEKUYPER LUSCIOUS PEACHTREE', 3917, 5) """
con.execute(query)

In [10]:
#cek apakah data benar" sudah masuk
query = """ SELECT * FROM stock; """
pd.read_sql_query(query, con)

                  item_description  stock_available  grade_rating
0       JAGERMEISTER MINI MEISTERS             3437           3.0
1   MAKERS MARK W/HOLIDAY ORNAMENT             4821           5.0
2          CROWN ROYAL W/2 GLASSES             2095           4.0
3            BLACK VELVET TRAVELER             2731           5.0
4       CANADIAN RICH & RARE PEACH             1661           4.0
5           FOUR ROSES SMALL BATCH             1837           5.0
6      OLD FORESTER BOURBON 86 PRF             3990           5.0
7                     TEN HIGH PET             1490           4.0
8                   ABSOLUT APEACH             3451           5.0
9                FRIS DANISH VODKA             3033           4.0
10           WESTERN SON BLUEBERRY             1906           4.0
11               CRUZAN STRAWBERRY             1584           5.0
12        BAILEYS VANILLA CINNAMON             3025           5.0
13                   KAHLUA COFFEE             4309           4.0
14     DEKUYPER LUSCIOUS PEACHTREE             3917           5.0

# 4. Buat 1 tabel dengan nama "sales" yang diimpor dari file excel

In [11]:
#library untuk membaca file xlsx
!pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [12]:
df = pd.read_excel('/content/sales.xlsx', engine='openpyxl')
print(df.head())

   store_number                            store_name         city  \
0          5052  CASEY'S GENERAL STORE #3220 / GREENF   GREENFIELD
1          4317      FAREWAY STORES #941 / GREENFIELD   GREENFIELD
2          5052  CASEY'S GENERAL STORE #3220 / GREENF   GREENFIELD
3          4472        QUICK SHOP FOODS / CENTERVILLE  CENTERVILLE
4          4419                  KUM & GO #4 / LAMONI       LAMONI

   county_number     county                 category_name  item_number  \
0              1      ADAIR                    SPICED RUM        43025
1              1      ADAIR             CANADIAN WHISKIES        10550
2              1      ADAIR             CANADIAN WHISKIES        11786
3              4  APPANOOSE             CANADIAN WHISKIES        11776
4             27    DECATUR  IMPORTED CORDIALS & LIQUEURS        65259

                item_description  pack  bottle_volume_ml  state_bottle_cost  \
0  ADMIRAL NELSON SPICED RUM PET    12               750               6.00
1   BLACK VELVET TOASTED CARAMEL    12               750               6.75
2          BLACK VELVET TRAVELER    12               750               5.23
3                   BLACK VELVET    12               750               5.23
4     JAGERMEISTER MINI MEISTERS    12                20               4.93

   state_bottle_retail  bottles_sold  sale_dollars
0                 9.00            24        216.00
1                10.13            24        243.12
2                 7.85            24        188.40
3                 7.85            24        188.40
4                 7.40             1          7.40

In [13]:
df.to_sql('sales', con, index=False)

1000

In [14]:
#cek info dalam table stock
query = """ PRAGMA table_info(sales); """
pd.read_sql_query(query, con)

    cid                 name     type  notnull dflt_value  pk
0     0         store_number  INTEGER        0       None   0
1     1           store_name     TEXT        0       None   0
2     2                 city     TEXT        0       None   0
3     3        county_number  INTEGER        0       None   0
4     4               county     TEXT        0       None   0
5     5        category_name     TEXT        0       None   0
6     6          item_number  INTEGER        0       None   0
7     7     item_description     TEXT        0       None   0
8     8                 pack  INTEGER        0       None   0
9     9     bottle_volume_ml  INTEGER        0       None   0
10   10    state_bottle_cost     REAL        0       None   0
11   11  state_bottle_retail     REAL        0       None   0
12   12         bottles_sold  INTEGER        0       None   0
13   13         sale_dollars     REAL        0       None   0

In [15]:
#cek apakah data benar" sudah masuk
query = """ SELECT * FROM sales limit 5; """
pd.read_sql_query(query, con)

,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars
0,5052,CASEY'S GENERAL STORE #3220 / GREENF,GREENFIELD,1,ADAIR,SPICED RUM,43025,ADMIRAL NELSON SPICED RUM PET,12,750,6.00,9.00,24,216.00
1,4317,FAREWAY STORES #941 / GREENFIELD,GREENFIELD,1,ADAIR,CANADIAN WHISKIES,10550,BLACK VELVET TOASTED CARAMEL,12,750,6.75,10.13,24,243.12
2,5052,CASEY'S GENERAL STORE #3220 / GREENF,GREENFIELD,1,ADAIR,CANADIAN WHISKIES,11786,BLACK VELVET TRAVELER,12,750,5.23,7.85,24,188.40
3,4472,QUICK SHOP FOODS / CENTERVILLE,CENTERVILLE,4,APPANOOSE,CANADIAN WHISKIES,11776,BLACK VELVET,12,750,5.23,7.85,24,188.40
4,4419,KUM & GO #4 / LAMONI,LAMONI,27,DECATUR,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER MINI MEISTERS,12,20,4.93,7.40,1,7.40

# 5. Tambahkan kolom "rating" pada tabel "sales" dengan tipe data float

In [17]:
#syntax untuk menambahkan kolom "rating" dengan tipe dat
query = """ ALTER TABLE sales ADD COLUMN rating FLOAT; """
con.execute(query)

In [18]:
#cek data dalam tabel rating
query = """ PRAGMA table_info(sales) """
pd.read_sql_query(query, con)

    cid                 name     type  notnull dflt_value  pk
0     0         store_number  INTEGER        0       None   0
1     1           store_name     TEXT        0       None   0
2     2                 city     TEXT        0       None   0
3     3        county_number  INTEGER        0       None   0
4     4               county     TEXT        0       None   0
5     5        category_name     TEXT        0       None   0
6     6          item_number  INTEGER        0       None   0
7     7     item_description     TEXT        0       None   0
8     8                 pack  INTEGER        0       None   0
9     9     bottle_volume_ml  INTEGER        0       None   0
10   10    state_bottle_cost     REAL        0       None   0
11   11  state_bottle_retail     REAL        0       None   0
12   12         bottles_sold  INTEGER        0       None   0
13   13         sale_dollars     REAL        0       None   0
14   14               rating    FLOAT        0       None   0

# 6. Lakukan Pembaharuan

**a. Data pada variabel pack yang memiliki category_name CREAM LIQUEURS diubah menjadi 40**

In [22]:
#cek data dengan category_name cream liqueurs
query = """ SELECT pack, category_name FROM sales WHERE category_name = 'CREAM LIQUEURS'; """
pd.read_sql_query(query, con)

    pack   category_name
0     12  CREAM LIQUEURS
1     12  CREAM LIQUEURS
2     12  CREAM LIQUEURS
3     12  CREAM LIQUEURS
4     12  CREAM LIQUEURS
5     12  CREAM LIQUEURS
6     12  CREAM LIQUEURS
7     12  CREAM LIQUEURS
8     12  CREAM LIQUEURS
9     12  CREAM LIQUEURS
10    12  CREAM LIQUEURS
11    12  CREAM LIQUEURS
12    12  CREAM LIQUEURS
13     6  CREAM LIQUEURS
14     6  CREAM LIQUEURS
15    12  CREAM LIQUEURS
16    12  CREAM LIQUEURS
17    12  CREAM LIQUEURS

In [23]:
#update variabel pack menjadi 40
query = """ UPDATE sales SET pack = 40 WHERE category_name = 'CREAM LIQUEURS' """
con.execute(query)

In [24]:
#cek datanya lagi
query = """ SELECT pack, category_name FROM sales WHERE category_name = 'CREAM LIQUEURS'; """
pd.read_sql_query(query, con)

    pack   category_name
0     40  CREAM LIQUEURS
1     40  CREAM LIQUEURS
2     40  CREAM LIQUEURS
3     40  CREAM LIQUEURS
4     40  CREAM LIQUEURS
5     40  CREAM LIQUEURS
6     40  CREAM LIQUEURS
7     40  CREAM LIQUEURS
8     40  CREAM LIQUEURS
9     40  CREAM LIQUEURS
10    40  CREAM LIQUEURS
11    40  CREAM LIQUEURS
12    40  CREAM LIQUEURS
13    40  CREAM LIQUEURS
14    40  CREAM LIQUEURS
15    40  CREAM LIQUEURS
16    40  CREAM LIQUEURS
17    40  CREAM LIQUEURS

**b. Data pada variabel sale_dollars yang memiliki  item_descriptions TITOS HANDMADE VODKA diubah menjadi 400**

In [26]:
#cek data dengan item_descriptions TITOS HANDMADE VODKA
query = """ SELECT sale_dollars, item_description FROM sales WHERE item_description = 'TITOS HANDMADE VODKA'; """
pd.read_sql_query(query, con)

    sale_dollars      item_description
0         360.00  TITOS HANDMADE VODKA
1         360.00  TITOS HANDMADE VODKA
2         360.00  TITOS HANDMADE VODKA
3         347.04  TITOS HANDMADE VODKA
4         347.04  TITOS HANDMADE VODKA
5         360.00  TITOS HANDMADE VODKA
6         360.00  TITOS HANDMADE VODKA
7         360.00  TITOS HANDMADE VODKA
8         360.00  TITOS HANDMADE VODKA
9         347.04  TITOS HANDMADE VODKA
10        360.00  TITOS HANDMADE VODKA
11        347.04  TITOS HANDMADE VODKA
12        360.00  TITOS HANDMADE VODKA
13        360.00  TITOS HANDMADE VODKA
14        360.00  TITOS HANDMADE VODKA
15        360.00  TITOS HANDMADE VODKA
16        360.00  TITOS HANDMADE VODKA
17        360.00  TITOS HANDMADE VODKA
18        360.00  TITOS HANDMADE VODKA
19        360.00  TITOS HANDMADE VODKA
20        347.04  TITOS HANDMADE VODKA
21        360.00  TITOS HANDMADE VODKA
22        360.00  TITOS HANDMADE VODKA
23        360.00  TITOS HANDMADE VODKA
24        347.04  TITOS HANDMADE VODKA
25        360.00  TITOS HANDMADE VODKA
26        347.04  TITOS HANDMADE VODKA
27        360.00  TITOS HANDMADE VODKA
28        360.00  TITOS HANDMADE VODKA
29        390.24  TITOS HANDMADE VODKA
30        347.04  TITOS HANDMADE VODKA
31        360.00  TITOS HANDMADE VODKA
32        360.00  TITOS HANDMADE VODKA
33        360.00  TITOS HANDMADE VODKA
34        360.00  TITOS HANDMADE VODKA
35        360.00  TITOS HANDMADE VODKA
36        360.00  TITOS HANDMADE VODKA
37        360.00  TITOS HANDMADE VODKA
38        360.00  TITOS HANDMADE VODKA
39        360.00  TITOS HANDMADE VODKA
40        347.04  TITOS HANDMADE VODKA
41        360.00  TITOS HANDMADE VODKA
42        347.04  TITOS HANDMADE VODKA
43        360.00  TITOS HANDMADE VODKA
44        347.04  TITOS HANDMADE VODKA
45        360.00  TITOS HANDMADE VODKA
46        360.00  TITOS HANDMADE VODKA
47        360.00  TITOS HANDMADE VODKA
48        347.04  TITOS HANDMADE VODKA
49        360.00  TITOS HANDMADE VODKA
50        360.00  TITOS HANDMADE VODKA

In [27]:
#update variabel sale_dollars yang memiliki item_descriptions TITOS HANDMADE VODKA diubah menjadi 400
query = """ UPDATE sales SET sale_dollars = 400 WHERE item_description = 'TITOS HANDMADE VODKA'; """
con.execute(query)

In [28]:
#cek data lagi
query = """ SELECT sale_dollars, item_description FROM sales WHERE item_description = 'TITOS HANDMADE VODKA'; """
pd.read_sql_query(query, con)

    sale_dollars      item_description
0          400.0  TITOS HANDMADE VODKA
1          400.0  TITOS HANDMADE VODKA
2          400.0  TITOS HANDMADE VODKA
3          400.0  TITOS HANDMADE VODKA
4          400.0  TITOS HANDMADE VODKA
5          400.0  TITOS HANDMADE VODKA
6          400.0  TITOS HANDMADE VODKA
7          400.0  TITOS HANDMADE VODKA
8          400.0  TITOS HANDMADE VODKA
9          400.0  TITOS HANDMADE VODKA
10         400.0  TITOS HANDMADE VODKA
11         400.0  TITOS HANDMADE VODKA
12         400.0  TITOS HANDMADE VODKA
13         400.0  TITOS HANDMADE VODKA
14         400.0  TITOS HANDMADE VODKA
15         400.0  TITOS HANDMADE VODKA
16         400.0  TITOS HANDMADE VODKA
17         400.0  TITOS HANDMADE VODKA
18         400.0  TITOS HANDMADE VODKA
19         400.0  TITOS HANDMADE VODKA
20         400.0  TITOS HANDMADE VODKA
21         400.0  TITOS HANDMADE VODKA
22         400.0  TITOS HANDMADE VODKA
23         400.0  TITOS HANDMADE VODKA
24         400.0  TITOS HANDMADE VODKA
25         400.0  TITOS HANDMADE VODKA
26         400.0  TITOS HANDMADE VODKA
27         400.0  TITOS HANDMADE VODKA
28         400.0  TITOS HANDMADE VODKA
29         400.0  TITOS HANDMADE VODKA
30         400.0  TITOS HANDMADE VODKA
31         400.0  TITOS HANDMADE VODKA
32         400.0  TITOS HANDMADE VODKA
33         400.0  TITOS HANDMADE VODKA
34         400.0  TITOS HANDMADE VODKA
35         400.0  TITOS HANDMADE VODKA
36         400.0  TITOS HANDMADE VODKA
37         400.0  TITOS HANDMADE VODKA
38         400.0  TITOS HANDMADE VODKA
39         400.0  TITOS HANDMADE VODKA
40         400.0  TITOS HANDMADE VODKA
41         400.0  TITOS HANDMADE VODKA
42         400.0  TITOS HANDMADE VODKA
43         400.0  TITOS HANDMADE VODKA
44         400.0  TITOS HANDMADE VODKA
45         400.0  TITOS HANDMADE VODKA
46         400.0  TITOS HANDMADE VODKA
47         400.0  TITOS HANDMADE VODKA
48         400.0  TITOS HANDMADE VODKA
49         400.0  TITOS HANDMADE VODKA
50         400.0  TITOS HANDMADE VODKA

**c. Data pada variabel item _description yang memiliki category_name AMERICAN VODKAS menjadi MCCORMICK 80PRF VODKA**

In [29]:
#cek data dengan category_name AMERICAN VODKAS
query = """ SELECT item_description, category_name FROM sales WHERE category_name = 'AMERICAN VODKAS'; """
pd.read_sql_query(query, con)

            item_description    category_name
0              HAWKEYE VODKA  AMERICAN VODKAS
1     FIVE O'CLOCK PET VODKA  AMERICAN VODKAS
2         FIVE O'CLOCK VODKA  AMERICAN VODKAS
3              HAWKEYE VODKA  AMERICAN VODKAS
4          HAWKEYE VODKA PET  AMERICAN VODKAS
..                       ...              ...
280           SMIRNOFF 80PRF  AMERICAN VODKAS
281  SMIRNOFF PEACH LEMONADE  AMERICAN VODKAS
282     TITOS HANDMADE VODKA  AMERICAN VODKAS
283     TITOS HANDMADE VODKA  AMERICAN VODKAS
284        HAWKEYE VODKA PET  AMERICAN VODKAS

[285 rows x 2 columns]

In [30]:
#update item description
query = """ UPDATE sales SET item_description = 'MCCORMICK 80PRF VODKA' WHERE category_name = 'AMERICAN VODKAS'; """
con.execute(query)

In [31]:
#cek data lagi
query = """ SELECT item_description, category_name FROM sales WHERE category_name = 'AMERICAN VODKAS'; """
pd.read_sql_query(query, con)

          item_description    category_name
0    MCCORMICK 80PRF VODKA  AMERICAN VODKAS
1    MCCORMICK 80PRF VODKA  AMERICAN VODKAS
2    MCCORMICK 80PRF VODKA  AMERICAN VODKAS
3    MCCORMICK 80PRF VODKA  AMERICAN VODKAS
4    MCCORMICK 80PRF VODKA  AMERICAN VODKAS
..                     ...              ...
280  MCCORMICK 80PRF VODKA  AMERICAN VODKAS
281  MCCORMICK 80PRF VODKA  AMERICAN VODKAS
282  MCCORMICK 80PRF VODKA  AMERICAN VODKAS
283  MCCORMICK 80PRF VODKA  AMERICAN VODKAS
284  MCCORMICK 80PRF VODKA  AMERICAN VODKAS

[285 rows x 2 columns]

**d. Entry data yang memiliki nilai bottles_sold kurang dari 20 dihapus**

In [33]:
#cek data dengan nilai bottles_sold kurang dari 20
query = """ SELECT * FROM sales WHERE bottles_sold < 20; """
pd.read_sql_query(query, con)

,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,4419,KUM & GO #4 / LAMONI,LAMONI,27,DECATUR,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER MINI MEISTERS,12,20,4.93,7.40,1,7.40,None
1,4533,CASEY'S GENERAL STORE #1985 / ST. ANSGAR,ST ANSGAR,66,MITCHELL,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER LIQUEUR MINI MEISTERS,12,20,4.93,7.40,1,7.40,None
2,3723,J D SPIRITS LIQUOR,ONAWA,67,MONONA,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER LIQUEUR MINI MEISTERS,12,20,4.93,7.40,1,7.40,None
3,2614,HY-VEE #3 FOOD & DRUGSTORE / DAVENPORT,DAVENPORT,82,SCOTT,IMPORTED CORDIALS & LIQUEURS,65259,JAGERMEISTER LIQUEUR MINI MEISTERS,12,20,4.93,7.40,1,7.40,None
4,4046,J AND K MARKET,CENTERVILLE,4,APPANOOSE,CANADIAN WHISKIES,10555,BLACK VELVET TOASTED CARAMEL,24,375,3.07,4.61,5,23.05,None
5,5268,THE DEPOT ATKINS,ATKINS,6,BENTON,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
6,2572,HY-VEE FOOD STORE / CEDAR FALLS,CEDAR FALLS,7,BLACK HAWK,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
7,3717,THE LIQUOR STOP / SUMNER,SUMNER,9,BREMER,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.60,5,23.00,None
8,2290,AL'S LIQUORS UNLIMITED,STORM LAKE,11,BUENA VISTA,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.60,5,23.00,None
9,2806,OSCO #881 / CLINTON,CLINTON,23,CLINTON,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
10,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.24,10.85,5,54.25,None
11,2616,HY-VEE FOOD AND DRUG / CLINTON,CLINTON,23,CLINTON,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
12,4873,CASEY'S GENERAL STORE #2559 / GRANGE,GRANGER,25,DALLAS,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
13,4898,BURLINGTON SHELL,BURLINGTON,29,DES MOINES,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,8.00,12.00,5,60.00,None
14,2506,HY-VEE #1044 / BURLINGTON,BURLINGTON,29,DES MOINES,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
15,4524,CASEY'S GENERAL STORE #1139 / NORA SPRINGS,NORA SPRINGS,34,FLOYD,CANADIAN WHISKIES,10805,CROWN ROYAL REGAL APPLE,24,375,8.00,12.00,5,60.00,None
16,4690,SUPER STOP AND SHOP / BALDWIN,BALDWIN,49,JACKSON,CANADIAN WHISKIES,10805,CROWN ROYAL REGAL APPLE,24,375,8.00,12.00,5,60.00,None
17,2517,HY-VEE FOOD STORE #1 / NEWTON,NEWTON,50,JASPER,CANADIAN WHISKIES,10624,CANADIAN CLUB WHISKY,24,375,4.28,6.42,5,32.10,None
18,2517,HY-VEE FOOD STORE #1 / NEWTON,NEWTON,50,JASPER,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
19,4604,PIT STOP LIQUORS / NEWTON,NEWTON,50,JASPER,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.65,11.48,5,57.40,None
20,2487,ANAMOSA FAMILY FOODS,ANAMOSA,53,JONES,CANADIAN WHISKIES,10624,CANADIAN CLUB WHISKY,24,375,4.28,6.42,5,32.10,None
21,2590,HY-VEE FOOD STORE #5 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
22,2552,HY-VEE FOOD STORE #3 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
23,5172,UPTOWN LIQUOR & TOBACCO,CEDAR RAPIDS,57,LINN,CANADIAN WHISKIES,10805,CROWN ROYAL REGAL APPLE,24,375,8.00,12.00,5,60.00,None
24,3403,ECON-O-MART / COLUMBUS JUNCTION,COLUMBUS JUNCTION,58,LOUISA,SCOTCH WHISKIES,5345,JOHNNIE WALKER RED,24,375,8.00,12.00,5,60.00,None
25,4362,KUM & GO #135 / POLK CITY,POLK CITY,77,POLK,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
26,4446,QUIK TRIP #513 / URBANDALE,URBANDALE,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
27,4368,KUM & GO #570 / JOHNSTON,JOHNSTON,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,8.00,12.00,5,60.00,None
28,4622,QUIK TRIP #544 / SE 14TH DM,DES MOINES,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,8.00,12.00,5,60.00,None
29,5057,KUM & GO #535 / DES MOINES,DES MOINES,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,8.00,12.00,5,60.00,None
30,4478,U S GAS,DES MOINES,77,POLK,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.75,11.63,5,58.15,None
31,4301,SAHOTA FOOD MART,DES MOINES,77,POLK,SCOTCH WHISKIES,5325,JOHNNIE WALKER BLACK,24,375,11.50,17.25,5,86.25,None
32,2587,HY-VEE FOOD STORE / JOHNSTON,JOHNSTON,77,POLK,SCOTCH WHISKIES,5345,JOHNNIE WALKER RED,24,375,7.50,11.24,5,56.20,None
33,2567,HY-VEE DRUGSTORE / DAVENPORT,DAVENPORT,82,SCOTT,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
34,3917,SMOKIN' JOE'S #2 TOBACCO AND LIQUOR OUTLET,DAVENPORT,82,SCOTT,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
35,4296,CIRCLE B MARKET,KEOSAUQUA,89,VAN BUREN,CANADIAN WHISKIES,11774,BLACK VELVET,24,375,3.07,4.61,5,23.05,None
36,2621,HY-VEE FOOD STORE #3 / SIOUX CITY,SIOUX CITY,97,WOODBURY,CANADIAN WHISKIES,11294,CROWN ROYAL CANADIAN WHISKY,24,375,7.65,11.48,5,57.40,None
37,5606,SA TOBACCO LIQUOR MART,CLINTON,23,CLINTON,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
38,2528,HY-VEE FOOD STORE #3 / DES MOINES,DES MOINES,77,POLK,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
39,5107,KUM & GO #4098 / WINDSOR HEIGHTS,WINDSOR HEIGHTS,77,POLK,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
40,2501,HY-VEE #2 / AMES,AMES,85,STORY,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
41,5065,CIRCLE S GORDON DRIVE,SIOUX CITY,97,WOODBURY,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
42,4454,KUM & GO #248 / SIOUX CITY,SIOUX CITY,97,WOODBURY,WHISKEY LIQUEUR,64858,FIREBALL CINNAMON WHISKEY MINI DISPENSER,1,3000,30.00,45.00,6,270.00,None
43,2201,HAPPY'S WINE & SPIRITS WHOLESALE,CEDAR FALLS,7,BLACK HAWK,CREAM LIQUEURS,73053,RUMCHATA,6,1000,17.00,25.50,18,459.00,None
44,3944,SAM'S CLUB 4973 / DUBUQUE,DUBUQUE,31,DUBUQUE,IMPORTED VODKAS,34422,GREY GOOSE,6,1000,22.75,34.13,18,614.34,None
45,5102,WILKIE LIQUORS,MOUNT VERNON,57,LINN,IMPORTED VODKAS,34422,GREY GOOSE,6,1000,19.00,28.50,18,513.00,None
46,5102,WILKIE LIQUORS,MOUNT VERNON,57,LINN,IMPORTED VODKAS,34422,GREY GOOSE,6,1000,22.75,34.13,18,614.34,None
47,3385,SAM'S CLUB 8162 / CEDAR RAPIDS,CEDAR RAPIDS,57,LINN,STRAIGHT RYE WHISKIES,27175,TEMPLETON 4YR RYE,6,1000,21.00,31.50,18,567.00,None
48,4829,CENTRAL CITY 2,DES MOINES,77,POLK,IMPORTED DRY GINS,28627,HENDRICK'S GIN,6,1000,21.17,31.76,18,571.68,None
49,4829,CENTRAL CITY 2,DES MOINES,77,POLK,STRAIGHT BOURBON WHISKIES,22217,WOODFORD RESERVE,6,1000,26.49,39.74,18,715.32,None
50,4829,CENTRAL CITY 2,DES MOINES,77,POLK,STRAIGHT BOURBON WHISKIES,22217,WOODFORD RESERVE,6,1000,26.49,39.74,18,715.32,None
51,4312,I-80 LIQUOR / COUNCIL BLUFFS,COUNCIL BLUFFS,78,POTTAWATTAMIE,IMPORTED VODKAS,34422,GREY GOOSE,6,1000,22.75,34.13,18,614.34,None
52,2625,HY-VEE WINE & SPIRITS #2 / DAVENPORT,DAVENPORT,82,SCOTT,100% AGAVE TEQUILA,87511,1800 SILVER,6,1000,18.00,27.00,18,486.00,None

In [35]:
#hapus data dengan nilai bottles_sold kurang dari 20
query = """ DELETE FROM sales WHERE bottles_sold < 20; """
con.execute(query)

In [36]:
#cek data dengan nilai bottles_sold kurang dari 20
query = """ SELECT * FROM sales WHERE bottles_sold < 20; """
pd.read_sql_query(query, con)

Empty DataFrame
Columns: [store_number, store_name, city, county_number, county, category_name, item_number, item_description, pack, bottle_volume_ml, state_bottle_cost, state_bottle_retail, bottles_sold, sale_dollars, rating]
Index: []

**e. Entry data yang memiliki nilai sale_dollars kurang dari 100 dan lebih dari 1000 dihapus**

In [38]:
#cek data dengan nilai sale_dollars kurang dari 100 dan lebih dari 1000
query = """ SELECT * FROM sales WHERE sale_dollars < 100 OR sale_dollars > 1000; """
pd.read_sql_query(query, con)

,store_number,store_name,city,county_number,county,category_name,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,rating
0,3494,SAM'S CLUB 6514 / WATERLOO,WATERLOO,7,BLACK HAWK,100% AGAVE TEQUILA,88296,PATRON SILVER,12,750,28.00,42.00,24,1008.00,None
1,5251,NORTHSIDE LIQUOR,MASON CITY,17,CERRO GORDO,100% AGAVE TEQUILA,89175,DON JULIO ANEJO,6,750,34.49,51.74,24,1241.76,None
2,3814,COSTCO WHOLESALE #788 / WDM,WEST DES MOINES,25,DALLAS,SINGLE MALT SCOTCH,4356,BALVENIE 12YR DOUBLEWOOD,12,750,32.50,48.75,24,1170.00,None
3,6242,WALL TO WALL WINE AND SPIRITS / WEST DES MOINES,WEST DES MOINES,25,DALLAS,IMPORTED CORDIALS & LIQUEURS,66056,NONINO AMARO QUINTESSENTIA,6,750,31.31,46.97,24,1127.28,None
4,2512,HY-VEE WINE AND SPIRITS / IOWA CITY,IOWA CITY,52,JOHNSON,100% AGAVE TEQUILA,87485,DON JULIO BLANCO,6,750,29.50,44.25,24,1062.00,None
5,2521,HY-VEE FOOD AND DRUG / GRAND / WDM,WEST DES MOINES,77,POLK,CORN WHISKIES,26613,FOUNDRY CORN WHISKEY,6,750,40.00,60.00,24,1440.00,None
6,2536,HY-VEE / PLEASANT HILL,PLEASANT HILL,77,POLK,AMERICAN VODKAS,36301,MCCORMICK 80PRF VODKA,12,50,4.13,6.20,360,2232.00,None
7,2478,PRAIRIE MEADOWS,ALTOONA,77,POLK,100% AGAVE TEQUILA,88296,PATRON SILVER,12,750,28.00,42.00,24,1008.00,None
8,4255,FAREWAY STORES #058 / ORANGE CITY,ORANGE CITY,84,SIOUX,TEMPORARY & SPECIALTY PACKAGES,13062,CROWN ROYAL W/ALTERNATE BAG,12,750,15.07,22.61,53,1198.07,None

In [39]:
#hapus data dengan nilai sale_dollars > 1000 dan < 100
query = """ DELETE FROM sales WHERE sale_dollars < 100 OR sale_dollars > 1000; """
con.execute(query)

In [40]:
#cek data lagi
query = """ SELECT * FROM sales WHERE sale_dollars < 100 OR sale_dollars > 1000; """
pd.read_sql_query(query, con)

Empty DataFrame
Columns: [store_number, store_name, city, county_number, county, category_name, item_number, item_description, pack, bottle_volume_ml, state_bottle_cost, state_bottle_retail, bottles_sold, sale_dollars, rating]
Index: []